AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Fifty shades of serverless application
    
Resources:
  UploadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: se.jiderhamn.serverless.aws.AwsHandler::handleRequest
      Runtime: java8
      CodeUri: ./target/lambda.jar
      Events:
        Ping:
          Type: Api
          Properties:
            Path: /transform/{proxy+}
            Method: any

  PingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./target/lambda.jar
      Handler: se.jiderhamn.serverless.aws.PingHandler::handleRequest
      Runtime: java8
      Events:
        Ping:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /ping/{proxy+}
            Method: any

  ProcessS3ObjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: se.jiderhamn.serverless.aws.S3Handler::handleRequest
      Runtime: java8
      CodeUri: ./target/lambda.jar
      MemorySize: 512
      Timeout: 15
      Policies:
        - AmazonS3FullAccess
      Events:
        ProcessS3ObjectEvent:
          Type: S3
          Properties:
            Bucket: !Ref InBucket 
            Events: s3:ObjectCreated:*
  InBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fifty-shades-transform # Must be globally unique

  TransformSQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:      
      Handler: se.jiderhamn.serverless.aws.QueueHandler::handleRequest
      Runtime: java8
      CodeUri: ./target/lambda.jar
      MemorySize: 512
      Timeout: 15
      Policies:
        - AmazonSQSFullAccess 
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt InputSqsQueue.Arn
            BatchSize: 10

  InputSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 50shades-input
  ResultSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 50shades-result

#Outputs:
#
#    FiftyShadesApi:
#      Description: "API Gateway endpoint URL for Prod stage for Ping function"
#      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping/"
#
#    FiftyShadesFunction:
#      Description: "Ping Lambda Function ARN"
#      Value: !GetAtt FiftyShadesFunction.Arn
#
#    FiftyShadesFunctionIamRole:
#      Description: "Implicit IAM Role created for Ping function"
#      Value: !GetAtt FiftyShadesFunctionRole.Arn
